export const CATEGORIES = {
  hardware: { label: 'Hardware', color: 'amber' },
  software: { label: 'Software', color: 'blue' },
  network: { label: 'Network', color: 'teal' },
  'user-support': { label: 'User Support', color: 'purple' },
  setup: { label: 'Setup', color: 'green' },
  other: { label: 'Other', color: 'gray' },
}


export const TODAY = new Date().toISOString().split('T')[0]

const s = (text, level = 0) => ({ id: `s-${Math.random().toString(36).slice(2)}`, text, level, completed: false })

export const SAMPLE_DOCS = [
  {
    id: 'doc-1', title: 'PC Setup — Full Procedure', isDoc: true,
    category: 'setup', date: TODAY,
    description: 'Standard step-by-step procedure for setting up a new PC from scratch.',
    steps: [
      s('Disable Secure Boot in BIOS'),
      s('Boot from Windows ISO (USB)'),
      s('Shift + F10 → terminal → run: oobe\\bypassnro'),
      s('Name user: Uporabnik — no password'),
      s('Run Windows Update — install all updates'),
      s('HP Support Assistant → download and install hardware drivers'),
      s('Ninite: install 7zip, Chrome, VLC'),
      s('Adobe Reader — install separately (not via Ninite)'),
      s('Install computer-specific apps (e.g. ProXSign)'),
      s('Rename computer to specified hostname'),
      s('lusrmgr.msc → create and configure user accounts'),
    ],
    tags: ['setup', 'windows', 'ninite', 'bios'],
  },
  {
    id: 'doc-2', title: 'Print Spooler Fix', isDoc: true,
    category: 'hardware', date: TODAY,
    description: 'Standard fix for printer not responding or stuck print jobs.',
    steps: [
      s('Services → find "Print Spooler" → restart'),
      s('Navigate to: C:\\Windows\\System32\\spool\\PRINTERS'),
      s('Delete all files in the PRINTERS folder (temp files from stuck jobs)'),
      s('Restart PC'),
      s('If still failing: check printer driver — reinstall if needed'),
      s('Physically unplug and replug the printer'),
    ],
    tags: ['printer', 'spooler', 'services'],
  },
  {
    id: 'doc-3', title: 'Outlook Common Fixes', isDoc: true,
    category: 'software', date: TODAY,
    description: 'Reference for the most frequent Outlook issues and their fixes.',
    steps: [
      s('Crash on open → Win+R → outlook /safe → runs in safe mode'),
      s('Teams add-in crash → File → Options → Add-ins → disable Teams add-in'),
      s('Infinite O365 login → regedit → disable WAM (set value to 1)'),
      s('No O365 license: add DWORD ExcludeExplicitO365Endpoint=1 in AutoDiscover key'),
      s('PST size limit → regedit → Office\\16.0\\Outlook\\PST → MaxLargeFileSize'),
      s('Archiving → File → Archive → select date'),
      s('Profile corrupt → Control Panel → Mail → create new profile'),
    ],
    tags: ['outlook', 'office', 'registry', 'crash'],
  },
  {
    id: 'doc-4', title: 'Network Troubleshooting Steps', isDoc: true,
    category: 'network', date: TODAY,
    description: 'Standard flow for diagnosing and fixing network connectivity problems.',
    steps: [
      s('ipconfig /release && ipconfig /renew — refresh IP lease'),
      s('ipconfig /all — verify IP address and DNS'),
      s('Ping gateway to test local network'),
      s('Device Manager → delete network adapter driver → restart (reinstalls)'),
      s('⚠ DNS changes: always apply on ETH cable, NOT WiFi'),
      s('Check documentation spreadsheet for correct IP / DNS values'),
      s('Update shortcut or Remote Desktop with new IP after network changes'),
    ],
    tags: ['network', 'ipconfig', 'dns', 'eth'],
  },
  {
    id: 'doc-5', title: 'Event Viewer — Diagnosing Errors', isDoc: true,
    category: 'software', date: TODAY,
    description: 'How to use Windows Event Viewer to find the root cause of crashes and errors.',
    steps: [
      s('Win + S → search "Event Viewer" → open'),
      s('Windows Logs → Application: app crashes, software issues'),
      s('Windows Logs → System: drivers, hardware, OS-level problems'),
      s('Windows Logs → Security: login events (usually safe to ignore)'),
      s('Filter by "Critical" and "Error" level first'),
      s('Note the Event ID and Source — use these to search for the fix'),
    ],
    tags: ['event-viewer', 'diagnostics', 'windows', 'logs'],
  },
  {
    id: 'doc-6', title: 'Adding a Network Printer via IP', isDoc: true,
    category: 'hardware', date: TODAY,
    description: 'Universal steps for adding a printer using its IP address.',
    steps: [
      s('Run Advanced IP Scanner to find printer IP on the network'),
      s('Settings → Bluetooth & devices → Printers & scanners → Add device'),
      s('Choose "Add manually" → "Add a printer using TCP/IP address"'),
      s('Enter printer IP address'),
      s('Download the correct driver from manufacturer website'),
      s('Set as default printer if needed'),
      s('Test print'),
    ],
    tags: ['printer', 'ip', 'driver', 'network'],
  },
  {
    id: 'doc-7', title: 'Scan to Folder Setup (Network Scanner)', isDoc: true,
    category: 'hardware', date: TODAY,
    description: 'Configure scanner to save directly to a network folder.',
    steps: [
      s('Open printer/scanner admin panel (via IP in browser)'),
      s('Go to Scan Destination / Address Book settings'),
      s('Set destination path: \\\\PC-hostname\\scan or \\\\IP\\scan'),
      s('If hostname fails → use IP address instead (more reliable)'),
      s('Ensure destination folder exists on the target PC'),
      s('Share the folder: right-click → Properties → Sharing → Share'),
      s('Security tab → Add user with full permissions'),
      s('Test scan'),
    ],
    tags: ['scanner', 'scan-to-folder', 'hostname', 'permissions'],
  },
  {
    id: 'doc-8', title: 'VPN Setup & Common Fix', isDoc: true,
    category: 'network', date: TODAY,
    description: 'Setting up VPN and fixing common connection issues.',
    steps: [
      s('Check documentation for VPN server address and credentials'),
      s('VPN Settings → Add VPN → enter server details'),
      s('If connection denied → Settings → VPN → Edit → re-enter password'),
      s('⚠ Cannot connect on work WiFi → switch to mobile hotspot first, connect VPN, then switch back'),
      s('Global Protect: if account locked → admin must unlock/reactivate'),
    ],
    tags: ['vpn', 'network', 'credentials'],
  },
]

export const SAMPLE_NOTES = [
  // ── 16.3 ─────────────────────────────────────────
  {
    id: 'n-1603-1', title: 'CPU Throttle 0.3GHz — ThrottleStop Fix', date: '2026-03-16',
    category: 'hardware', priority: 'high',
    description: 'CPU capped at 0.3GHz after Windows security (KBS) update was downloaded.',
    steps: [
      s('CPU throttled to 0.3GHz — caused by KBS Windows security update'),
      s('Try ThrottleStop utility to unlock CPU performance'),
      s('Check battery settings and power plan'),
      s('Run stress test to verify CPU speed'),
      s('Tried uninstalling the problematic KBS security update'),
      s('Problem occurred specifically after KBS update download'),
    ],
    tags: ['cpu', 'throttlestop', 'windows-update', 'kbs'], createdAt: '2026-03-16T08:00:00Z', updatedAt: '2026-03-16T08:00:00Z',
  },
  {
    id: 'n-1603-2', title: 'PC Full Setup Guide', date: '2026-03-16',
    category: 'setup', priority: 'medium',
    description: 'Standard procedure for fresh Windows installation and PC configuration.',
    steps: [
      s('Copy existing user files before reinstall'),
      s('Disable BIOS Secure Boot (Security Boot Control)'),
      s('Install Windows fresh'),
      s('Run Windows Update — install all updates'),
      s('Download drivers via HP Support'),
      s('Use Ninite for default apps (Chrome, 7zip, VLC, etc.)'),
      s('Run lusrmgr.msc to create and configure new user accounts'),
    ],
    tags: ['setup', 'windows', 'ninite', 'lusrmgr', 'drivers'], createdAt: '2026-03-16T09:00:00Z', updatedAt: '2026-03-16T09:00:00Z',
  },
  {
    id: 'n-1603-3', title: 'Advanced IP Scanner + ISL Remote Access', date: '2026-03-16',
    category: 'software', priority: 'low',
    description: 'Key tools used on the job. ISL is Slovenian TeamViewer alternative.',
    steps: [
      s('Advanced IP Scanner — scan network to find devices by IP (printers, PCs)'),
      s('ISL Online — Slovenian remote access tool (like TeamViewer)'),
      s('Use ISL for remote support sessions'),
    ],
    tags: ['ip-scanner', 'isl', 'tools', 'remote-access'], createdAt: '2026-03-16T10:00:00Z', updatedAt: '2026-03-16T10:00:00Z',
  },
  {
    id: 'n-1603-4', title: 'Printer Removal + App Reinstall (Corrupted)', date: '2026-03-16',
    category: 'hardware', priority: 'medium',
    description: 'Removing printer using old Devices and Printers menu. Reinstalling corrupted app.',
    steps: [
      s('To remove printer: open Devices and Printers using \\ (backslash) for old Windows menu'),
      s('Remove printer from device list'),
      s('For corrupted app: locate new .exe file in company files'),
      s('Install fresh .exe to desktop'),
      s('Old shortcut had corrupted path or outdated program version'),
      s('Also: first check PC runtime before troubleshooting (uptime check)'),
    ],
    tags: ['printer', 'devices', 'app-reinstall', 'corrupt'], createdAt: '2026-03-16T11:00:00Z', updatedAt: '2026-03-16T11:00:00Z',
  },

  // ── 17.3 ─────────────────────────────────────────
  {
    id: 'n-1703-1', title: 'HP LaserJet p01102w — Driver + User Setup', date: '2026-03-17',
    category: 'hardware', priority: 'high',
    description: 'Printer connected to PC, driver missing. Used lusrmgr for ISL credential check.',
    steps: [
      s('HP LaserJet p01102w connected directly to computer'),
      s('Download new driver for the printer model'),
      s('Open lusrmgr.msc — check ISL credentials and administrator rights'),
      s('Install drivers, set printer as default'),
      s('Restart PC after driver install'),
    ],
    tags: ['hp', 'printer', 'driver', 'lusrmgr'], createdAt: '2026-03-17T08:00:00Z', updatedAt: '2026-03-17T08:00:00Z',
  },
  {
    id: 'n-1703-2', title: 'Disk Health Check + Secure Overwrite', date: '2026-03-17',
    category: 'hardware', priority: 'medium',
    description: 'Testing disks, checking health, secure overwriting for data safety.',
    steps: [
      s('Win + X → Disk Management (Upravljalec diskov)'),
      s('For unrecognized disks: create new GPT or MBR instance'),
      s('Run disk diagnostics: defragmentation + error check'),
      s('CrystalDiskInfo — check disk usage time and health status'),
      s('Macrorit Data Wiper — 3-pass DoD overwrite for secure data erasure'),
    ],
    tags: ['disk', 'crystaldiskinfo', 'macrorit', 'health', 'wipe'], createdAt: '2026-03-17T09:00:00Z', updatedAt: '2026-03-17T09:00:00Z',
  },
  {
    id: 'n-1703-3', title: 'Teams Access Fix + App Installation (Antivirus/Backup)', date: '2026-03-17',
    category: 'software', priority: 'medium',
    description: 'Teams no admin rights → web version. Installing company default apps.',
    steps: [
      s('No admin rights for desktop Teams → use web Teams temporarily'),
      s('Fix: set Teams as startup application'),
      s('Pin Teams to taskbar for easy access'),
      s('For app installation: download from company stored defaults'),
      s('Enter company credentials during install'),
    ],
    tags: ['teams', 'antivirus', 'backup', 'install'], createdAt: '2026-03-17T10:00:00Z', updatedAt: '2026-03-17T10:00:00Z',
  },
  {
    id: 'n-1703-4', title: 'Outlook Archiving + Network Printer via IP + DWG', date: '2026-03-17',
    category: 'software', priority: 'low',
    description: 'Archiving Outlook emails, adding IP printer, DWG viewer for SVG/DWG files.',
    steps: [
      s('Outlook archive: File → Archive → Select date'),
      s('Add network printer: select IP address → download drivers → choose correct drivers'),
      s('DWG viewer — software for opening SVG and DWG files'),
    ],
    tags: ['outlook', 'archive', 'printer', 'dwg', 'svg'], createdAt: '2026-03-17T11:00:00Z', updatedAt: '2026-03-17T11:00:00Z',
  },

  // ── 18.3 ─────────────────────────────────────────
  {
    id: 'n-1803-1', title: 'Event Viewer — Diagnostics Guide', date: '2026-03-18',
    category: 'software', priority: 'high',
    description: 'Using Windows Event Viewer to find critical errors and diagnose problems.',
    steps: [
      s('Open Event Viewer (event logger for problem finding)'),
      s('Application log → app crashes, software issues'),
      s('System log → drivers, hardware, OS-level problems'),
      s('Security log → logins (usually can ignore)'),
      s('Check for Critical errors first'),
    ],
    tags: ['event-viewer', 'diagnostics', 'logs', 'windows'], createdAt: '2026-03-18T08:00:00Z', updatedAt: '2026-03-18T08:00:00Z',
  },
  {
    id: 'n-1803-2', title: 'Tails OS — Secure Anonymous Operating System', date: '2026-03-18',
    category: 'other', priority: 'low',
    description: 'Security-focused live OS. All traffic routed through Tor. Leaves no traces.',
    steps: [
      s('Tor-based OS — all internet connections automatically routed through Tor'),
      s('Amnesic — forgets everything after shutdown, leaves no traces on PC'),
      s('Comes with: Tor Browser, KeePassXC (passwords)'),
      s('GnuPG — email/file encryption'),
      s('Electrum — cryptocurrency'),
      s('OnionShare — anonymous file sharing'),
    ],
    tags: ['tails', 'tor', 'security', 'privacy', 'keepass'], createdAt: '2026-03-18T09:00:00Z', updatedAt: '2026-03-18T09:00:00Z',
  },
  {
    id: 'n-1803-3', title: 'Active Directory + Domain Check + Chrome Workspace Fix', date: '2026-03-18',
    category: 'network', priority: 'medium',
    description: 'ISL + domain check via AD. Chrome default pages opening in wrong workspace.',
    steps: [
      s('Connect via ISL, check domain membership in Windows'),
      s('Active Directory → verify user permissions and domain'),
      s('If domain: check AD for rights. If no domain → local password'),
      s('Chrome not opening default pages → check Win+Tab (other workspace open)'),
      s('PDF download permissions error → allow unsafe, allow redirects'),
    ],
    tags: ['active-directory', 'domain', 'chrome', 'isl'], createdAt: '2026-03-18T10:00:00Z', updatedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: 'n-1803-4', title: 'Outlook Archive + Excel Version Restore + Mail Signout Fix', date: '2026-03-18',
    category: 'software', priority: 'low',
    description: 'Multiple Office tasks: archive emails by year, restore Excel version, mail quick fix.',
    steps: [
      s('Mail quick fix: sign out and sign in again → solves most mail issues immediately'),
      s('Outlook archive by year: reduces mailbox space'),
      s('Excel: restore previous version from File → Version History'),
    ],
    tags: ['outlook', 'excel', 'archive', 'office'], createdAt: '2026-03-18T11:00:00Z', updatedAt: '2026-03-18T11:00:00Z',
  },
  {
    id: 'n-1803-5', title: 'Nextcloud 2FA Problem + Ransomware Note + Hak5/OverTheWire', date: '2026-03-18',
    category: 'other', priority: 'low',
    description: 'Nextcloud first login 2FA issue. Ransomware infection encountered. Cybersec learning resources.',
    steps: [
      s('Nextcloud first login problem → 2FA code not working'),
      s('Not our problem → different IT team handles it, cannot fix 2FA'),
      s('Encountered PC infected with ransomware'),
      s('Hak5 — hardware hacking learning tools/resources'),
      s('OverTheWire — online cybersecurity wargames/learning'),
    ],
    tags: ['nextcloud', '2fa', 'ransomware', 'security', 'learning'], createdAt: '2026-03-18T12:00:00Z', updatedAt: '2026-03-18T12:00:00Z',
  },

  // ── 19.3 ─────────────────────────────────────────
  {
    id: 'n-1903-1', title: 'O365 Infinite Login Prompt — Disable WAM (Registry)', date: '2026-03-19',
    category: 'software', priority: 'high',
    description: 'O365 keeps asking for login credentials in a loop. Fix via registry WAM disable.',
    steps: [
      s('Open Registry Editor (regedit)'),
      s('Navigate to: HKEY_CURRENT_USER\\Software\\...\\Office\\16.0'),
      s('Find the relevant WAM key and set value to 1'),
    ],
    tags: ['o365', 'office', 'registry', 'login', 'wam'], createdAt: '2026-03-19T08:00:00Z', updatedAt: '2026-03-19T08:00:00Z',
  },

  // ── 23.3 ─────────────────────────────────────────
  {
    id: 'n-2303-1', title: 'Outlook O365 Error: ExcludeExplicitO365Endpoint Fix', date: '2026-03-23',
    category: 'software', priority: 'high',
    description: 'Client has no O365 license. Outlook tries O365 autodiscover and fails. Fix via registry.',
    steps: [
      s('Control Panel → Outlook Mail → create new account (need client data)'),
      s('No O365 license — need correct path for mail server'),
      s('Navigate to: HKEY_CURRENT_USER\\Software\\Microsoft\\Office\\16.0\\Outlook\\AutoDiscover'),
      s('If AutoDiscover key missing: right-click Outlook key → New → Key → name "AutoDiscover"'),
      s('Inside AutoDiscover: right-click → New → DWORD (32-bit) Value'),
      s('Name it: ExcludeExplicitO365Endpoint → set value to 1'),
      s('Restart laptop'),
      s('If still broken: recreate Outlook profile'),
      s('FIX FOR CLIENTS WITHOUT O365 — uses Exchange Server instead'),
    ],
    tags: ['outlook', 'o365', 'registry', 'autodiscover', 'exchange'], createdAt: '2026-03-23T08:00:00Z', updatedAt: '2026-03-23T08:00:00Z',
  },
  {
    id: 'n-2303-2', title: 'WiFi / ETH Cable Network Problem', date: '2026-03-23',
    category: 'network', priority: 'high',
    description: 'Network connectivity issue. Multiple fix attempts for WiFi and ETH.',
    steps: [
      s('Fix 1: ipconfig /release && ipconfig /renew'),
      s('Note: "no operation can be performed on wifi while it has its media..." → wait'),
      s('Fix 2: ipconfig /all → check IP and confirm internet access'),
      s('Fix 3: Device Manager → delete ETH cable driver → restart PC'),
      s('Also: use Revo Uninstaller for complete app removal'),
    ],
    tags: ['network', 'wifi', 'eth', 'ipconfig', 'driver'], createdAt: '2026-03-23T09:00:00Z', updatedAt: '2026-03-23T09:00:00Z',
  },
  {
    id: 'n-2303-3', title: 'PC Setup — Updated Full Instructions', date: '2026-03-23',
    category: 'setup', priority: 'medium',
    description: 'Refined PC setup process with all numbered steps.',
    steps: [
      s('1) Disable Secure Boot in BIOS'),
      s('2) Boot ISO for specified Windows version'),
      s('3) Shift + F10 to open terminal during Windows setup'),
      s('4) Run: oobe\\bypassnro — bypass Windows network setup requirement'),
      s('5) Name user: Uporabnik — no password'),
      s('6) Run Windows Update — install all updates'),
      s('7) HP Support — download and install hardware drivers'),
      s('8) Ninite: install 7zip, Chrome, VLC'),
      s('9) Adobe Reader — install separately (not via Ninite)'),
      s('10) Install computer-specific apps (e.g. ProXSign)'),
      s('11) Change hostname to specified name (rename computer)'),
    ],
    tags: ['setup', 'windows', 'ninite', 'bios', 'proxsign'], createdAt: '2026-03-23T10:00:00Z', updatedAt: '2026-03-23T10:00:00Z',
  },
  {
    id: 'n-2303-4', title: 'Meeting Room Screen Problem + VPN Palma Fix', date: '2026-03-23',
    category: 'network', priority: 'medium',
    description: 'Presentation screen access issue (no permissions to shared folder). VPN re-auth fix.',
    steps: [
      s('Meeting room screen error: user has no access to \\\\FS\\Skupno\\1_finance'),
      s('No permissions to 1_finance folder → error'),
      s('Fix: Add network location → right-click "This PC" → Add network location'),
      s('VPN Palma "remote connection denied" → VPN Settings → Edit → re-enter password'),
    ],
    tags: ['meeting-room', 'permissions', 'vpn', 'shared-folder'], createdAt: '2026-03-23T11:00:00Z', updatedAt: '2026-03-23T11:00:00Z',
  },

  // ── 24.3 ─────────────────────────────────────────
  {
    id: 'n-2403-1', title: 'Teren — Ptuj, Rogaška, Celje Field Work', date: '2026-03-24',
    category: 'setup', priority: 'medium',
    description: 'Full day of field work across three locations.',
    steps: [
      s('Ptuj: Set up two computers and lay network cables'),
      s('Rogaška Slatina: Disconnect and remove Mercator devices'),
      s('Celje (Modial): Swap/replace printer'),
    ],
    tags: ['teren', 'field', 'ptuj', 'rogaska', 'celje'], createdAt: '2026-03-24T08:00:00Z', updatedAt: '2026-03-24T08:00:00Z',
  },

  // ── 25.3 ─────────────────────────────────────────
  {
    id: 'n-2503-1', title: 'Server Access + IP Change After Network Swap', date: '2026-03-25',
    category: 'network', priority: 'high',
    description: 'Server access issues after network IP change. Update documentation and shortcuts.',
    steps: [
      s('Network change → old IPs no longer valid'),
      s('Check documentation spreadsheet for new IP address'),
      s('Update Remote Desktop shortcut with new IP'),
      s('Update documentation with new IP (replace old with new)'),
      s('Repeat for each client with broken connection after IP change'),
    ],
    tags: ['ip-change', 'remote-desktop', 'network', 'documentation'], createdAt: '2026-03-25T08:00:00Z', updatedAt: '2026-03-25T08:00:00Z',
  },
  {
    id: 'n-2503-2', title: 'Java Required for Anchor Validation', date: '2026-03-25',
    category: 'software', priority: 'medium',
    description: 'Validated and rejected anchors problem — required Java to be installed.',
    steps: [
      s('Problem with extensions → needed Java'),
      s('Download Java offline installer'),
      s('Install Java → anchors validation works'),
    ],
    tags: ['java', 'anchors', 'extension'], createdAt: '2026-03-25T09:00:00Z', updatedAt: '2026-03-25T09:00:00Z',
  },
  {
    id: 'n-2503-3', title: 'Halcom Nexsus PIN Reset (Blocked)', date: '2026-03-25',
    category: 'user-support', priority: 'high',
    description: 'Halcom Nexsus Personal blocked/locked. PIN change and resolution.',
    steps: [
      s('Nexsus locked → need to change PIN'),
      s('Set new PIN in Nexsus Personal app'),
      s('If still blocked → contact Halcom company to resolve'),
    ],
    tags: ['halcom', 'nexsus', 'pin', 'blocked'], createdAt: '2026-03-25T10:00:00Z', updatedAt: '2026-03-25T10:00:00Z',
  },
  {
    id: 'n-2503-4', title: 'Teren — Printer + Cables + Monitors + PC Handover', date: '2026-03-25',
    category: 'setup', priority: 'medium',
    description: 'Field work tasks on 25.3.',
    steps: [
      s('Swap/replace printer + organise cables + replace UTP cables'),
      s('Receive/take over a computer'),
      s('Replace monitors'),
      s('Hand over computer'),
      s('BONUS: DNS server on computer — document for reference'),
    ],
    tags: ['teren', 'field', 'printer', 'cables', 'dns'], createdAt: '2026-03-25T11:00:00Z', updatedAt: '2026-03-25T11:00:00Z',
  },

  // ── 26.3 ─────────────────────────────────────────
  {
    id: 'n-2603-1', title: 'Locked Authentication Account (Admin Unlock)', date: '2026-03-26',
    category: 'user-support', priority: 'high',
    description: 'User account locked for authentication. Admin unlock + Global Protect issue.',
    steps: [
      s('Account locked for authentication → admin must unlock / reactivate'),
      s('Received confirmation from user'),
      s('Also: Global Protect VPN issue encountered'),
    ],
    tags: ['account', 'locked', 'admin', 'globalprotect'], createdAt: '2026-03-26T08:00:00Z', updatedAt: '2026-03-26T08:00:00Z',
  },
  {
    id: 'n-2603-2', title: 'Outlook Sending + E-poslovanje IP Problem', date: '2026-03-26',
    category: 'software', priority: 'medium',
    description: 'Outlook not sending email. E-poslovanje IP issue after network change.',
    steps: [
      s('Outlook sending problem → test by sending to own Gmail'),
      s('Fix: add info mail address for outgoing mail'),
      s('E-poslovanje: cannot connect → IP change needed'),
      s('Check documentation spreadsheet for documented IP change'),
      s('Update IP shortcut with new IP'),
      s('If correct IP but still no access → no permissions to the server'),
    ],
    tags: ['outlook', 'email', 'e-poslovanje', 'ip'], createdAt: '2026-03-26T09:00:00Z', updatedAt: '2026-03-26T09:00:00Z',
  },
  {
    id: 'n-2603-3', title: 'POS Terminal DNS Fix (Use ETH Not WiFi!)', date: '2026-03-26',
    category: 'network', priority: 'high',
    description: 'POS terminal not connecting to server. DNS fix — must use ETH cable, not WiFi.',
    steps: [
      s('POS terminal not connected to server'),
      s('Network and Sharing Center → WiFi → Internet Protocol IPv4'),
      s('Use manual DNS → enter documented DNS addresses (primary + secondary)'),
      s('⚠ USE ETH CABLE CONNECTION — NOT WIFI'),
      s('WiFi DNS change causes errors'),
      s('DNS fix applied on ETH cable → POS terminal connects'),
    ],
    tags: ['pos', 'dns', 'eth', 'terminal', 'network'], createdAt: '2026-03-26T10:00:00Z', updatedAt: '2026-03-26T10:00:00Z',
  },
  {
    id: 'n-2603-4', title: 'DNS / VPN / IP Fixes', date: '2026-03-26',
    category: 'network', priority: 'medium',
    description: 'Hyperlink access via DNS/VPN, IP update, DNS for ETH cable connection.',
    steps: [
      s('Hyperlink no access: try VPN first'),
      s('If VPN fails: manually change DNS server to documented address'),
      s('Replace IP in shortcut with new documented IP'),
      s('Change DNS server for ETH (not WiFi) to enable UTP cable connection'),
    ],
    tags: ['dns', 'vpn', 'ip', 'network'], createdAt: '2026-03-26T11:00:00Z', updatedAt: '2026-03-26T11:00:00Z',
  },

  // ── 30.3 ─────────────────────────────────────────
  {
    id: 'n-3003-1', title: 'Outlook Crashing: Teams Add-on Fix', date: '2026-03-30',
    category: 'software', priority: 'high',
    description: 'Outlook crashing on open. Fixed by disabling Teams add-in in Outlook.',
    steps: [
      s('Outlook crashes immediately on open'),
      s('Try: Win+R → outlook /safe (safe mode — this works)'),
      s('Check Account Settings for issues'),
      s('User Accounts → create new Outlook profile → give profile name'),
      s('Re-add Outlook account in new profile'),
      s('If wrong username: try alternate username format (e.g. postar.pri/...)'),
      s('If still crashing: Control Panel → Programs → Office → Change → Repair'),
      s('Check Event Viewer → find Outlook crash reason'),
      s('Redownload and install C++ Redistributable'),
      s('⭐ FIX: File → Options → Add-ins → disable Teams Add-in → Outlook stops crashing'),
    ],
    tags: ['outlook', 'crash', 'teams-addon', 'safe-mode', 'office-repair'], createdAt: '2026-03-30T08:00:00Z', updatedAt: '2026-03-30T08:00:00Z',
  },
  {
    id: 'n-3003-2', title: 'Outlook PST Size Registry Fix (50-100GB)', date: '2026-03-30',
    category: 'software', priority: 'medium',
    description: 'Outlook PST file size limit causing problems. Fix via registry MaxLargeFileSize.',
    steps: [
      s('Open Registry Editor (regedit)'),
      s('Navigate to: HKEY_CURRENT_USER\\Software\\Microsoft\\Office\\16.0\\Outlook\\PST'),
      s('Right-click → New → DWORD (32-bit) Value'),
      s('Name it: MaxLargeFileSize'),
      s('Set value to desired size in MB (e.g. 102400 for 100GB)'),
    ],
    tags: ['outlook', 'pst', 'registry', 'size-limit'], createdAt: '2026-03-30T09:00:00Z', updatedAt: '2026-03-30T09:00:00Z',
  },
  {
    id: 'n-3003-3', title: 'Printer Spooler + Hardware Problem', date: '2026-03-30',
    category: 'hardware', priority: 'high',
    description: 'Blagajna/printer issue. Spooler fix and hardware diagnosis.',
    steps: [
      s('Services → Print Spooler → restart service'),
      s('Navigate to: C:\\Windows\\System32\\spool\\PRINTERS → delete all temp files'),
      s('Restart PC after clearing spooler'),
      s('If print still fails: check printer driver'),
      s('Unplug and replug printer physically'),
      s('VirusTotal — scan files for viruses if needed'),
      s('Restart PC again'),
      s('⚠ Hardware issue — old printer → ordered replacement'),
    ],
    tags: ['printer', 'spooler', 'hardware', 'services'], createdAt: '2026-03-30T10:00:00Z', updatedAt: '2026-03-30T10:00:00Z',
  },
  {
    id: 'n-3003-4', title: 'Ricoh Scanner: Hostname Fix + Runtime Error', date: '2026-03-30',
    category: 'hardware', priority: 'medium',
    description: 'Ricoh printer/scanner login issue. Changed IP to PC hostname. Also: CrystalDecision runtime error.',
    steps: [
      s('CrystalDecision runtime error "max report processing jobs limit reached" → restart PC → fixed'),
      s('Login to Ricoh admin panel'),
      s('cmd → type: hostname → copy the PC hostname'),
      s('In Ricoh: change IP address setting to PC hostname'),
      s('Device Management → Address Book → change User 001'),
      s('Change IP field to PC hostname → enter PC password'),
      s('Remote desktop connection problem (investigate separately)'),
    ],
    tags: ['ricoh', 'scanner', 'hostname', 'crystaldecision'], createdAt: '2026-03-30T11:00:00Z', updatedAt: '2026-03-30T11:00:00Z',
  },

  // ── 31.3 ─────────────────────────────────────────
  {
    id: 'n-3103-1', title: 'Adobe Reader Default PDF + Remote Desktop IP', date: '2026-03-31',
    category: 'software', priority: 'low',
    description: 'Set Adobe Reader as default PDF app. Update remote desktop IP from documentation.',
    steps: [
      s('Download Adobe Acrobat Reader'),
      s('Set as default app for PDF files'),
      s('Remote desktop: replace old IP with new documented IP'),
    ],
    tags: ['adobe', 'pdf', 'remote-desktop', 'ip'], createdAt: '2026-03-31T08:00:00Z', updatedAt: '2026-03-31T08:00:00Z',
  },

  // ── 1.4 ─────────────────────────────────────────
  {
    id: 'n-0104-1', title: 'Lexmark Scan to Folder Fix', date: '2026-04-01',
    category: 'hardware', priority: 'high',
    description: 'Lexmark printer not scanning to folder. Missing folder + permissions fix.',
    steps: [
      s('Lexmark printer → go to Scan Destination settings'),
      s('Go to specific user → check scan-to-folder path'),
      s('Path was: /LOm2/scan2 → but user only had /LOm2/scan (no scan2 folder)'),
      s('Create folder scan2 → then add sharing permissions'),
      s('Share settings → Security → Edit → Add → new user'),
      s('Add scan user with full permissions'),
    ],
    tags: ['lexmark', 'scanner', 'scan-to-folder', 'permissions'], createdAt: '2026-04-01T08:00:00Z', updatedAt: '2026-04-01T08:00:00Z',
  },
  {
    id: 'n-0104-2', title: 'Certificate, Monitor/Dock, Domain Password', date: '2026-04-01',
    category: 'user-support', priority: 'medium',
    description: 'Digital certificate via SI PASS TRUST. Monitor dock issue. Domain PC password check.',
    steps: [
      s('Navigate to SI PASS TRUST website → review new certificate request'),
      s('HP Support Assistant → update drivers for dock/monitor'),
      s('PC is on domain → no user wants to login → check credentials'),
      s('Check if computer is on domain (Active Directory) → verify credentials'),
    ],
    tags: ['certificate', 'sipass', 'monitor', 'dock', 'domain'], createdAt: '2026-04-01T09:00:00Z', updatedAt: '2026-04-01T09:00:00Z',
  },
  {
    id: 'n-0104-3', title: 'Turist App Setup (Date Format + VPN)', date: '2026-04-01',
    category: 'setup', priority: 'medium',
    description: 'Turist application setup: remove old users, set date format, configure IE + Outlook + VPN.',
    steps: [
      s('Remove old users from PC'),
      s('Turist app: set correct date/time format from documentation'),
      s('Sign in to Internet Explorer'),
      s('Sign in to Outlook'),
      s('Prepare and configure VPN for the user'),
    ],
    tags: ['turist', 'date-format', 'vpn', 'outlook', 'setup'], createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-01T10:00:00Z',
  },

  // ── 2.4 ─────────────────────────────────────────
  {
    id: 'n-0204-1', title: 'VPN Problem: Personal Hotspot Workaround', date: '2026-04-02',
    category: 'network', priority: 'high',
    description: 'Cannot connect to VPN while on work WiFi (Gea College). Hotspot workaround.',
    steps: [
      s('Client connected to Gea College work WiFi → VPN connection denied'),
      s('Cannot connect to VPN while already on work network'),
      s('Workaround: set up personal mobile hotspot'),
      s('Switch PC to mobile hotspot WiFi'),
      s('Set up VPN using documentation instructions'),
      s('After VPN connects: can then switch back to Gea College work WiFi'),
    ],
    tags: ['vpn', 'wifi', 'hotspot', 'gea-college'], createdAt: '2026-04-02T08:00:00Z', updatedAt: '2026-04-02T08:00:00Z',
  },
  {
    id: 'n-0204-2', title: 'Scan to Folder: IP vs Hostname', date: '2026-04-02',
    category: 'hardware', priority: 'medium',
    description: 'Scanner not connecting to destination folder. Using IP instead of hostname fixed it.',
    steps: [
      s('Try changing destination to hostname → did not work'),
      s('Check folder destination path — must match exactly'),
      s('Try using IP address instead of hostname'),
      s('Fix: \\\\10.3.x.x\\scan (IP format) worked instead of hostname'),
    ],
    tags: ['scanner', 'scan-to-folder', 'hostname', 'ip'], createdAt: '2026-04-02T09:00:00Z', updatedAt: '2026-04-02T09:00:00Z',
  },
  {
    id: 'n-0204-3', title: 'Outlook Crash — Teams Add-on (Again) + Blagajna', date: '2026-04-02',
    category: 'software', priority: 'medium',
    description: 'Outlook crash from Teams add-on again. Blagajna crash → escalated.',
    steps: [
      s('Blagajna crashes → restart (long runtime) → if still crashing → not our issue → escalate'),
      s('Outlook crash on open → Teams add-on problem again'),
      s('File → Options → Add-ins → uncheck Teams add-in'),
      s('Microsoft add-in causing crash'),
    ],
    tags: ['outlook', 'teams-addon', 'blagajna', 'crash'], createdAt: '2026-04-02T10:00:00Z', updatedAt: '2026-04-02T10:00:00Z',
  },

  // ── 3.4 ─────────────────────────────────────────
  {
    id: 'n-0304-1', title: 'App Update: IBS Report + Vasco + gpupdate', date: '2026-04-03',
    category: 'software', priority: 'high',
    description: 'App update requiring credentials. IBS and Vasco install. Active Directory gpupdate fix.',
    steps: [
      s('Update apps → need credentials to proceed'),
      s('Check documentation for correct .ini file path'),
      s('Select and enter the correct .ini file'),
      s('Uninstall old app version first'),
      s('IBS Report app: testing EBN installed application'),
      s('Vasco download: from \\\\ieappgeneral\\vasco network path'),
      s('Alternative: vasco.si/datoteke → download first link'),
      s('After user change: run gpupdate /force to update Active Directory permissions'),
      s('Vasco issue: set correct date/time format in settings'),
    ],
    tags: ['ibs', 'vasco', 'gpupdate', 'active-directory', 'credentials'], createdAt: '2026-04-03T08:00:00Z', updatedAt: '2026-04-03T08:00:00Z',
  },
  {
    id: 'n-0304-2', title: 'Outlook 2FA Login Issue (Different Domain)', date: '2026-04-03',
    category: 'user-support', priority: 'medium',
    description: 'Outlook Classic 2FA setup. User has different email domain than others on same domain.',
    steps: [
      s('Set up Outlook Classic with 2FA authenticator'),
      s('Configure Microsoft Authenticator app'),
      s('Problem: user has different email format than others on same domain'),
      s('Check exact email format required for this user'),
    ],
    tags: ['outlook', '2fa', 'authenticator', 'domain', 'login'], createdAt: '2026-04-03T09:00:00Z', updatedAt: '2026-04-03T09:00:00Z',
  },
  {
    id: 'n-0304-3', title: 'Outlook Self-Fix, FileZilla, Adobe PDF Default', date: '2026-04-03',
    category: 'software', priority: 'low',
    description: 'Various small software tasks on 3.4.',
    steps: [
      s('Outlook issue → resolved on its own'),
      s('Download and install FileZilla FTP client'),
      s('Adobe Reader not opening PDFs (Edge opens instead)'),
      s('Adobe Reader fix: Settings → General → set "Open PDF at startup"'),
    ],
    tags: ['filezilla', 'adobe', 'pdf', 'outlook'], createdAt: '2026-04-03T10:00:00Z', updatedAt: '2026-04-03T10:00:00Z',
  },

  // ── 7.4 ─────────────────────────────────────────
  {
    id: 'n-0704-1', title: 'New User Full Setup (Outlook + Printer + OneDrive)', date: '2026-04-07',
    category: 'setup', priority: 'high',
    description: 'Complete new user setup: Outlook with 2FA, authenticator, printer, OneDrive, Edge.',
    steps: [
      s('Set up Outlook: mail + domain (@globalpharmacia.com)'),
      s('Set up Microsoft Authenticator — ⚠ phone MUST be on same work WiFi'),
      s('If authenticator not working → check phone WiFi network'),
      s('Login to Edge for sync'),
      s('Add printer: find IP in documentation → go to General settings'),
      s('Check printer IP and driver version → download correct drivers → upload'),
      s('Login to OneDrive'),
      s('Scan to email setup (instead of scan to folder)'),
      s('Register new user (JKL): login as administrator → add user'),
      s('Change PC password for new user'),
    ],
    tags: ['setup', 'outlook', 'onedrive', 'authenticator', 'printer', 'new-user'], createdAt: '2026-04-07T08:00:00Z', updatedAt: '2026-04-07T08:00:00Z',
  },
  {
    id: 'n-0704-2', title: 'HP Printer Not Found on IP Scanner', date: '2026-04-07',
    category: 'hardware', priority: 'medium',
    description: 'Adding HP printer but IP Scanner cannot find it on the network.',
    steps: [
      s('Run Advanced IP Scanner to find printer (HP model)'),
      s('Download and install printer driver'),
      s('Add printer and set as default'),
      s('⚠ HP printer not found on IP Scanner — needs further investigation'),
    ],
    tags: ['printer', 'hp', 'ip-scanner', 'driver'], createdAt: '2026-04-07T09:00:00Z', updatedAt: '2026-04-07T09:00:00Z',
  },
  {
    id: 'n-0704-3', title: 'Antivirus (Panda) Blocking Everything', date: '2026-04-07',
    category: 'other', priority: 'high',
    description: 'Panda Antivirus blocking Microsoft click-to-run and other services.',
    steps: [
      s('Antivirus (Panda) blocks Microsoft click-to-run service'),
      s('Open Panda admin console → find blocked item'),
      s('Unblock Microsoft click-to-run service'),
      s('Unblock specific programs for the user'),
    ],
    tags: ['panda', 'antivirus', 'blocked', 'click-to-run'], createdAt: '2026-04-07T10:00:00Z', updatedAt: '2026-04-07T10:00:00Z',
  },
]
